### ISSUE TITLE
Dead members coming alive again are soon wrongy recognized as dead again

### ISSUE THREAD

**Issue by chbndrhnns** [edwardcapriolo/gossip#15]
Hey, when I ran tests with multiple clients on my local machine I discovered this behavior:
- I shut down a client and wait until every other client knows about it
- I start the client again (heartbeat starts at 0)
- the new client is discovered again but after one or two iterations removed again for no obvious reason.

Did someone observe a similar behavior and has a fix to it?

**Comment by edwardcapriolo** [comment]
Is this random or does it happen every time. We should be able to provide a unit test that demonstrates this.

**Comment by chbndrhnns** [comment]
It happens every time to me. I created a test case (inherited from the existing tests) that demonstrates the issue:

`
    @Test
    public void DeadNodesDoNotComeAliveAgain() throws InterruptedException, UnknownHostException {
        GossipSettings settings = new GossipSettings();

        log.info( "Adding seed nodes" );
        int seedNodes = 3;
        List<GossipMember> startupMembers = new ArrayList<>();
        for (int i = 1; i < seedNodes+1; ++i) {
            startupMembers.add(new RemoteGossipMember("127.0.0.1", 50000 + i, i + ""));
        }

        log.info( "Adding clients" );
        final List<GossipService> clients = new ArrayList<>();
        final int clusterMembers = 5;
        for (int i = 1; i < clusterMembers+1; ++i) {
            GossipService gossipService = new GossipService("127.0.0.1", 50000 + i, i + "",
                    startupMembers, settings,
                    new GossipListener(){
                        @Override
                        public void gossipEvent(GossipMember member, GossipState state) {
                            System.out.println(member+" "+ state);
                        }
                    });
            clients.add(gossipService);
            gossipService.start();
        }
        TUnit.assertThat(new Callable<Integer> (){
            public Integer call() throws Exception {
                int total = 0;
                for (int i = 0; i < clusterMembers; ++i) {
                    total += clients.get(i).get_gossipManager().getMemberList().size();
                }
                return total;
            }}).afterWaitingAtMost(10, TimeUnit.SECONDS).isEqualTo(20);

        // shutdown one client and verify that one client is lost.
        Random r = new Random();
        int randomClientId = r.nextInt(clusterMembers);
        int shutdownPort = clients.get(randomClientId).get_gossipManager().getMyself().getPort();
        clients.get(randomClientId).shutdown();
        TUnit.assertThat(new Callable<Integer> (){
            public Integer call() throws Exception {
                int total = 0;
                for (int i = 0; i < clusterMembers; ++i) {
                    total += clients.get(i).get_gossipManager().getMemberList().size();
                }
                return total;
            }}).afterWaitingAtMost(10, TimeUnit.SECONDS).isEqualTo(16);

        // start client again
        GossipService gossipService = new GossipService("127.0.0.1", shutdownPort, shutdownPort + "",
                startupMembers, settings,
                new GossipListener(){
                    @Override
                    public void gossipEvent(GossipMember member, GossipState state) {
                        System.out.println(member+" "+ state);
                    }
                });
        clients.add(gossipService);
        gossipService.start();

        // verify that the client is alive again for every node
        TUnit.assertThat(new Callable<Integer> (){
            public Integer call() throws Exception {
                int total = 0;
                for (int i = 0; i < clusterMembers; ++i) {
                    total += clients.get(i).get_gossipManager().getMemberList().size();
                }
                return total;
            }}).afterWaitingAtMost(20, TimeUnit.SECONDS).isEqualTo(20);
        
    }
`

**Comment by edwardcapriolo** [comment]
Awesome! Nice use of tunit :) I will take a look at this. I feel like something similar has been reported before.

**Comment by chbndrhnns** [comment]
Hey there,

Google always corrected by search for "Tunit" by "Junit" - took me a while
to realize that.
I just do not know enough about advanced Java to fix it myself but I am
really interested in seing what is wrong there because I want to use it for
a project! :)

Bye,
Jo

2016-03-03 14:51 GMT-08:00 edwardcapriolo <notifications@github.com>:

**Comment by edwardcapriolo** [comment]
Sorry for the delay. I was looking at this. I changed your test a bit. The issue is that higher heartbeat messages win often and nodes ping pong state. So the answer here is to implement some type of hold down timer such that nodes that are recently revived are not so eagerly marked dead again. I will look at that later tonight.

**Comment by edwardcapriolo** [comment]
I have tuned up the code a bit, I think I am going to turn hearbeat into a timestamp so that it is easier to establish cronology. Right now when a node starts up again its heartbeat is 0 and its gossip never "wins" over older recrods.

**Comment by edwardcapriolo** [comment]
@chbndrhnns I noticed your test had one minor bug in that your were removing adding a new gossiper to the list and not removing the old one. Still there were other issues that I addressed. Can you give
https://github.com/edwardcapriolo/gossip/compare/ts_as_heartbeat?expand=1 a try and let me know your experience with it. If i dont hear from you in a few days I will merge

**Comment by chbndrhnns** [comment]
Hey, thanks very much for your work! While the new tests always pass, the timestamp heartbeat system does not work in my real life application. Maybe I can provide you with a test set that fails.
